### ISSUE TITLE
Enable support for custom calendar colours in the manifest file for events

### ISSUE THREAD

**Issue by DanielCordell** [HackSocNotts/hacksocnotts.github.io#95]
The calendar page should allow for different colors on the event items based on a type specified in the manifest.

The component should default all events as workshops, as these are our most common events.

The colors should be set in a config file, json or js is fine. 

Some proposed event types would be `workshop`, `speaker` ,`meetup` , `hackathon`, `hardware`

Manifest files could look like this:
```YML
- id: 2019-hardware-workshop-intro
  name: Hardware Workshop
  start: '2019-10-03 18:30:00'
  end: '2019-10-03 20:00:00'
  location: A32 - Ada Lovelace Lab
  mapLink: https://www.google.com/maps
  summary: 2019-hardware-workshop-intro/summary.md
  description: 2019-hardware-workshop-intro/description.md
  banner: 2019-hardware-workshop-intro/banner.jpg
  type: workshop
```
